.TH "mikutter" "1" 
.SH "NAME" 
mikutter \(em simply, powerfully, and modifully twitter client
.SH "SYNOPSIS" 
.PP 
\fBmikutter\fR [\fBoptions\fP]
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBmikutter\fR command. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
Instead, it has documentation in the GNU \fBInfo\fP format; see below. 
.PP 
\fBmikutter\fR is a simply, powerfully, and modifully twitter client.
This client has more than 3939 features by default.
.IP "   \(bu" 6 
Multi-pane
.IP "   \(bu" 6 
Show reply, threads, followers and followees, profile, list and user
activities
.IP "   \(bu" 6 
Search tweets
 
.SH "AUTHOR" 
.PP 
This manual page was written by Koichi Akabe vbkaisetsu@gmail.com for 
the \fBDebian\fP system (and may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 3 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License Version 3 can be found in /usr/share/common-licenses/GPL-3. 

